### ISSUE TITLE
todology not working

### ISSUE THREAD

**Issue by krushil1** [ariporad/todology#5]
Hi, 

I was trying to use todology, but it wasn't working. It kept giving me a lot of errors. I also tried installing the libraries manually but that still didn't fix the issue. If you can please take a look, it would help me a lot!! If you need my Schoology calendar link, let me know! I would be really happy to let you use it!!

**Comment by ariporad** [comment]
Hi @krushil1!

It's great to hear somebody is still using this! I confess that I've have since graduated high school and so haven't used todology in several years... which is to say that it's possible that the project is simply broken at this point.

However, would you mind uploading a screenshot of the entire error message that you're receiving? I'm happy to take a look and see if it's something straightforward.

**Comment by krushil1** [comment]
Hi @ariporad,

here is the screenshot with the errors I am getting, also, I am using python 3.9. 
<img width="1439" alt="Screen Shot 2021-01-06 at 10 32 41 AM" src="https://user-images.githubusercontent.com/41350747/103786710-bb778780-500a-11eb-921f-f0b08f1851d1.png">

**Comment by ariporad** [comment]
Hmm... it looks like Todoist has shut down that API. Unfortunately, this probably means that you'd need to update Todology to use the new API (if one exists). 

If you decide to go that route, let me know—I'm more than happy to let you take over the project and update the README with a link to your fork.

**Comment by krushil1** [comment]
Hey @ariporad, I will try working on it and if I do get it to work, I will definitely let you know!!! Thanks for your feedback!

**Comment by ariporad** [comment]
Sounds good! Happy to help!
